// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Dashboard from "./routes/Dashboard.tsx";
import * as $UserProfile from "./routes/UserProfile.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $resetpassword from "./routes/resetpassword.tsx";
import * as $FeaturedCourse from "./islands/FeaturedCourse.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $HeroSection from "./islands/HeroSection.tsx";
import * as $Instructors from "./islands/Instructors.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $PopularCourses from "./islands/PopularCourses.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $StudentReviews from "./islands/StudentReviews.tsx";
import * as $Testimonials from "./islands/Testimonials.tsx";
import * as $UniversityInfoproducerSection from "./islands/UniversityInfoproducerSection.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Dashboard.tsx": $Dashboard,
    "./routes/UserProfile.tsx": $UserProfile,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/resetpassword.tsx": $resetpassword,
  },
  islands: {
    "./islands/FeaturedCourse.tsx": $FeaturedCourse,
    "./islands/Footer.tsx": $Footer,
    "./islands/HeroSection.tsx": $HeroSection,
    "./islands/Instructors.tsx": $Instructors,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/PopularCourses.tsx": $PopularCourses,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/StudentReviews.tsx": $StudentReviews,
    "./islands/Testimonials.tsx": $Testimonials,
    "./islands/UniversityInfoproducerSection.tsx":
      $UniversityInfoproducerSection,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
